### ISSUE TITLE
E: Unable to locate package box86 

### ISSUE THREAD

**Issue by yahavb** [Itai-Nelken/weekly-box86-debs#11]
I am following the steps https://itai-nelken.github.io/weekly-box86-debs/ on `Linux ip-192-168-72-245 5.10.0-21-cloud-arm64 #1 SMP Debian 5.10.162-1 (2023-01-21) aarch64 GNU/Linux` and `Linux ip-192-168-86-202 5.15.0-1031-aws #35-Ubuntu SMP Fri Feb 10 02:12:38 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux` and get the same error `E: Unable to locate package box86`. The commands seems straight forward but still fails

```
admin@ip-192-168-72-245:~$ wget -qO- https://itai-nelken.github.io/weekly-box86-debs/add-repo.sh | sudo bash
adding repo...
 + sudo wget https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list -O /etc/apt/sources.list.d/box86.list
--2023-05-14 19:15:03--  https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list
Resolving itai-nelken.github.io (itai-nelken.github.io)... 185.199.110.153, 185.199.109.153, 185.199.108.153, ...
Connecting to itai-nelken.github.io (itai-nelken.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62 [text/plain]
Saving to: ‘/etc/apt/sources.list.d/box86.list’

/etc/apt/sources.list.d/box86. 100%[===================================================>]      62  --.-KB/s    in 0s      

2023-05-14 19:15:03 (7.81 MB/s) - ‘/etc/apt/sources.list.d/box86.list’ saved [62/62]

adding key...
 + wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
running apt update...
 + sudo apt update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://cdn-aws.deb.debian.org/debian bullseye InRelease                  
Hit:3 http://cdn-aws.deb.debian.org/debian bullseye-updates InRelease          
Hit:4 http://cdn-aws.deb.debian.org/debian bullseye-backports InRelease        
Hit:5 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
31 packages can be upgraded. Run 'apt list --upgradable' to see them.
DONE!
To install box86, run:
sudo apt install box86
admin@ip-192-168-72-245:~$ sudo apt install box86
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package box86
```

Any idea will be blessed :)

**Comment by Itai-Nelken** [comment]
The error happens because you are on a 64bit arm system and the package is for 32bit arm systems, so apt can't find the package because it doesn't exist for 64bit.

You can either use box64 if the software you want to run is x64, or use multiarch to be able to install box86.

A box64 debian repository by @ryanfortner is available here: https://box64.debian.ryanfortner.dev

To use multiarch, execute the following commands in the terminal.  
Do this at your own risk though, because, although it has never happened to me, multiarch can sometimes break your system.
```shell
sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install box86:armhf
```
Note that @ryanfortner also has a box86 repo that is better maintained and also has packages for generic arm machines (meaning not specific devices such as the rpi4) which might work better for you. 
It can be found here: https://box86.debian.ryanfortner.dev

**Comment by yahavb** [comment]
perfect and thanks Itai! The Serbian install worked well!
